### ISSUE TITLE
Support for using variables in the header.

### ISSUE THREAD

**Issue by duyafeng** [vearne/autotest#6]
For example, I plan to use the variable token in the header.
- id: 3
  dependOnIDs: [2]
  request:
    method: "put"
    url: "http://{{ HOST }}/api/books/{{ MY_BOOK_ID }}"
    headers:
      - "Content-Type: application/json"
      **- "Authorization: Bearer {{ TOKEN }}"**
    body: |
      {
          "title": "book3_title",
          "author": "book3_author-2"
      }
  rules:
    - name: "HttpStatusEqualRule"
      expectedStatus: 200
    - name: "HttpBodyEqualRule"
      xpath: "/author"
      Expected: "book3_author-2"

**Comment by vearne** [comment]
ok
